"""Exports the ten report definitions (same data as the PDFs) as reports-data.js for the daily planner.

Run:  python export_json.py [output_path]
It re-uses gen_reports.py: the PDF helpers are swapped for recorders, so the planner and the PDFs can never disagree.
"""
import json
import re
import sys

import gen_reports as g

cur = None
out = []


def strip(t):
    return re.sub(r"\s+", " ", str(t.text if hasattr(t, "text") else t)).strip()


def rec_table(header, rows, widths=None, align_right_from=1, bold_last=False, **kw):
    cur["blocks"].append({"t": "table", "head": [strip(h) for h in header],
                          "rows": [[strip(c) for c in r] for r in rows], "total": bool(bold_last)})
    return None


g.table = rec_table
g.chart_block = lambda title, cats, series: cur["blocks"].append(
    {"t": "chart", "title": title, "cats": [str(c) for c in cats], "series": [{"name": n, "data": [float(x) for x in d]} for n, d in series]})
g.kpis = lambda items: cur["blocks"].append({"t": "kpis", "items": [[strip(v), strip(l)] for v, l in items]})
g.h2 = lambda t: cur["blocks"].append({"t": "h", "text": strip(t)})
g.note = lambda t: cur["blocks"].append({"t": "note", "html": str(t)})
g.small = lambda t: cur["blocks"].append({"t": "small", "text": strip(t)})
g.body = lambda t: cur["blocks"].append({"t": "small", "text": strip(t)})


class _Stub:  # reportlab Table() in r6 wraps a recorded table; swallow it
    pass


g.Table = lambda *a, **k: type("T", (), {"setStyle": lambda self, s: None})()


def build(filename, title, subtitle, story, scope_line=None):
    cur.update(id=filename[:2], file=filename, title=title, question=subtitle)


g.build = build
for fn in (g.r1, g.r2, g.r3, g.r4, g.r5, g.r6, g.r7, g.r8, g.r9, g.r10):
    cur = {"blocks": []}
    fn()
    out.append(cur)

meta = {"farm": "Tanganyika Blue", "window": "2026-08-23 (closing balance) to 2026-09-23 (inclusive)",
        "source": g.D.PROJECT, "extract": g.D.EXTRACT}
path = sys.argv[1] if len(sys.argv) > 1 else "reports-data.js"
payload = {"meta": meta, "reports": out}
text = json.dumps(payload, ensure_ascii=False, indent=1)
if path.endswith(".json"):
    open(path, "w", encoding="utf-8").write(text + "\n")
else:
    open(path, "w", encoding="utf-8").write(
        "// Generated by export_json.py from the tb-farm mirror database - do not edit by hand.\n"
        "window.TB_REPORTS = " + text + ";\n")
print(path, [(r["id"], len(r["blocks"])) for r in out])
