CREATE TABLE IF NOT EXISTS "public"."activity_planner" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "farm_id" uuid NOT NULL,
    "created_by" uuid NOT NULL,
    "title" text NOT NULL,
    "notes" text DEFAULT ''::text NOT NULL,
    "scheduled_date" date NOT NULL,
    "planning_window" text NOT NULL,
    "status" text DEFAULT 'planned'::text NOT NULL,
    "completed_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "activity_planner_title_check" CHECK ((char_length("title") >= 1) AND (char_length("title") <= 120)),
    CONSTRAINT "activity_planner_planning_window_check" CHECK (("planning_window" = ANY (ARRAY['tomorrow'::text, 'this_week'::text]))),
    CONSTRAINT "activity_planner_status_check" CHECK (("status" = ANY (ARRAY['planned'::text, 'done'::text])))
);

ALTER TABLE "public"."activity_planner" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."activity_planner_reminder_delivery" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "activity_planner_id" uuid NOT NULL,
    "recipient_email" text NOT NULL,
    "reminder_date" date NOT NULL,
    "sent_at" timestamp with time zone DEFAULT now() NOT NULL,
    "provider_message_id" text
);

ALTER TABLE "public"."activity_planner_reminder_delivery" OWNER TO "postgres";

ALTER TABLE ONLY "public"."activity_planner"
    ADD CONSTRAINT "activity_planner_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."activity_planner_reminder_delivery"
    ADD CONSTRAINT "activity_planner_reminder_delivery_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."activity_planner_reminder_delivery"
    ADD CONSTRAINT "activity_planner_reminder_delivery_unique" UNIQUE ("activity_planner_id", "recipient_email", "reminder_date");

CREATE INDEX "idx_activity_planner_farm_date" ON "public"."activity_planner" USING btree ("farm_id", "scheduled_date");
CREATE INDEX "idx_activity_planner_status_date" ON "public"."activity_planner" USING btree ("status", "scheduled_date");
CREATE INDEX "idx_activity_planner_created_by" ON "public"."activity_planner" USING btree ("created_by");
CREATE INDEX "idx_activity_planner_reminder_date" ON "public"."activity_planner_reminder_delivery" USING btree ("reminder_date");

ALTER TABLE ONLY "public"."activity_planner"
    ADD CONSTRAINT "activity_planner_farm_id_fkey" FOREIGN KEY ("farm_id") REFERENCES "public"."farm"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."activity_planner"
    ADD CONSTRAINT "activity_planner_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."activity_planner_reminder_delivery"
    ADD CONSTRAINT "activity_planner_reminder_delivery_activity_id_fkey" FOREIGN KEY ("activity_planner_id") REFERENCES "public"."activity_planner"("id") ON DELETE CASCADE;

ALTER TABLE "public"."activity_planner" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."activity_planner_reminder_delivery" ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."activity_planner" TO "authenticated";
GRANT ALL ON TABLE "public"."activity_planner" TO "service_role";

GRANT SELECT ON TABLE "public"."activity_planner_reminder_delivery" TO "authenticated";
GRANT ALL ON TABLE "public"."activity_planner_reminder_delivery" TO "service_role";

GRANT ALL ON SEQUENCE "public"."activity_planner_reminder_delivery_id_seq" TO "service_role";

CREATE POLICY "activity_planner_select_farm_member" ON "public"."activity_planner"
FOR SELECT TO "authenticated"
USING ("private"."is_farm_member"("farm_id"));

CREATE POLICY "activity_planner_insert_write_roles" ON "public"."activity_planner"
FOR INSERT TO "authenticated"
WITH CHECK (
    "private"."has_farm_role"("farm_id", ARRAY['admin'::text, 'farm_manager'::text, 'system_operator'::text])
    AND "created_by" = ( SELECT "auth"."uid"() AS "uid")
);

CREATE POLICY "activity_planner_update_write_roles" ON "public"."activity_planner"
FOR UPDATE TO "authenticated"
USING ("private"."has_farm_role"("farm_id", ARRAY['admin'::text, 'farm_manager'::text, 'system_operator'::text]))
WITH CHECK ("private"."has_farm_role"("farm_id", ARRAY['admin'::text, 'farm_manager'::text, 'system_operator'::text]));

CREATE POLICY "activity_planner_delete_write_roles" ON "public"."activity_planner"
FOR DELETE TO "authenticated"
USING ("private"."has_farm_role"("farm_id", ARRAY['admin'::text, 'farm_manager'::text, 'system_operator'::text]));

CREATE POLICY "activity_planner_reminder_delivery_select_farm_member" ON "public"."activity_planner_reminder_delivery"
FOR SELECT TO "authenticated"
USING (
    EXISTS (
        SELECT 1
        FROM "public"."activity_planner" pa
        WHERE pa.id = "activity_planner_reminder_delivery"."activity_planner_id"
          AND "private"."is_farm_member"(pa.farm_id)
    )
);

CREATE OR REPLACE TRIGGER "trg_activity_planner_updated_at"
BEFORE UPDATE ON "public"."activity_planner"
FOR EACH ROW EXECUTE FUNCTION "private"."set_updated_at"();
