"use client"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { calculateFeed, planDays, validDate } from "@/features/analytics/feed-model"
import type { FeedPlan, FeedSource } from "@/features/analytics/feed-types"
import { saveFeedPlan } from "./actions"
const fmt=(n:number)=>n.toLocaleString("en-GB",{maximumFractionDigits:1})
const inputClass="w-28 rounded-lg border bg-background px-2 py-2 text-right"
export default function FeedPlanner({farmId,start,end,asOf,today,sources,saved,canSave}:{farmId:string;start:string;end:string;asOf:string;today:string;sources:FeedSource[];saved:FeedPlan|null;canSave:boolean}){
 const router=useRouter()
 const [rows,setRows]=useState(()=> (saved?.rows??sources).map(s=>({...s,include:true,stock:String(s.stock_no),abw:s.abw_g==null?"":String(s.abw_g),sample:s.sampled_on??""})))
 const [dirty,setDirty]=useState(false),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("")
 const from=saved?.starts_on??start,to=saved?.ends_on??end,cutoff=saved?.source_as_of??asOf
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=""};const link=(e:MouseEvent)=>{if((e.target as HTMLElement).closest("a[href]")&&!window.confirm("Leave without saving this feed plan?")){e.preventDefault();e.stopPropagation()}};window.addEventListener("beforeunload",warn);document.addEventListener("click",link,true);return()=>{window.removeEventListener("beforeunload",warn);document.removeEventListener("click",link,true)}},[dirty])
 const results=rows.map((r,i)=>{if(saved)return saved.rows[i].result;try{return r.stock!==""&&r.abw!==""?calculateFeed(Number(r.stock),Number(r.abw),from,to):null}catch{return null}})
 const included=rows.filter(r=>r.include)
 const invalid=rows.some((r,i)=>r.include&&(!results[i]||!r.sample||r.sample>cutoff))
 const total=rows.reduce((sum,r,i)=>sum+(r.include?(results[i]?.feed_kg??0):0),0)
 const change=(i:number,field:"stock"|"abw"|"sample"|"include",value:string|boolean)=>{setRows(old=>old.map((r,j)=>j===i?{...r,[field]:value}:r));setDirty(true);setConfirmed(false);setMessage("")}
 function csv(){const lines=[["Cage","Batch","Start date","End date","Stock source date","Sampling date","Starting fish","Starting ABW (g)","Expected end fish","Expected end ABW (g)","Feed (kg)","Average daily feed (kg)"]];rows.forEach((r,i)=>{const x=results[i];if(r.include&&x)lines.push([r.cage_name,r.batch_name,from,to,r.stock_date,r.sample,r.stock,r.abw,String(x.end_fish),x.end_abw_g.toFixed(3),x.feed_kg.toFixed(3),x.average_daily_kg.toFixed(3)])});const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([lines.map(line=>line.map(v=>'"'+v.replaceAll('"','""')+'"').join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}));a.download=`feed-plan-${from}-${to}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <div className="space-y-5">
  <div className="flex flex-wrap items-end gap-4">
   {!saved?<form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();if(dirty&&!window.confirm("Reload source records and discard unsaved inputs?"))return;const f=new FormData(e.currentTarget);const s=String(f.get("start")),eDate=String(f.get("end")),a=String(f.get("asOf"));try{planDays(s,eDate);if(!validDate(a)||a>today||a>s)throw new Error("Stock date must be on or before today and the plan start.")}catch(error){setMessage(error instanceof Error?error.message:"Check the dates.");return}setDirty(false);router.push(`/analytics/inputs/feed-planning?farmId=${farmId}&start=${f.get("start")}&end=${f.get("end")}&asOf=${f.get("asOf")}`)}}>
    <label className="text-sm">From<input required className="block rounded-lg border bg-background p-2" name="start" type="date" defaultValue={from}/></label>
    <label className="text-sm">To<input required className="block rounded-lg border bg-background p-2" name="end" type="date" defaultValue={to}/></label>
    <label className="text-sm">Stock as of<input required className="block rounded-lg border bg-background p-2" name="asOf" type="date" max={today} defaultValue={cutoff}/></label>
    <button className="rounded-lg border px-4 py-2">Load inputs</button>
   </form>:<p>Saved plan · {from} to {to}</p>}
  </div>
  <section className="rounded-xl border bg-card p-5 space-y-4">
   <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-2"><h2 className="text-lg font-semibold">Cage inputs</h2><details className="relative"><summary aria-label="About feed planning" className="cursor-pointer list-none rounded-full border px-2 text-sm">i</summary><div className="absolute left-0 top-8 z-20 w-80 rounded-xl border bg-background p-4 text-sm shadow-lg space-y-2"><p>TB model: starting weight selects a growth phase, mortality and eFCR. Expected feed equals net biomass gain × eFCR. Rates stay fixed for the period, matching the workbook’s normal feeding calculation.</p><p>Calendar months use the workbook’s monthly mortality. Custom periods scale survival on a 30-day basis. Average daily feed is a budgeting average, not a daily ration schedule.</p><p>Sources use the latest stocked cage and batch on or before the stock date. ABW is the latest measured sample for that cage/batch. Confirm missing or older values. Harvests, transfers and emergency rations during the plan are not forecast here.</p><p>Saving keeps the confirmed inputs and calculated results for this plan. Daily records and farm defaults are unchanged.</p></div></details></div><span className="text-sm text-muted-foreground">Model: TB</span></div>
   {rows.length===0?<p>No stocked cages were found on or before {cutoff}. Choose another stock date.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted"><tr>{["Use","Cage","Batch","Stock record","Sampled on","Starting fish","Starting ABW (g)","End fish","End ABW (g)","Feed (kg)","Avg/day (kg)"].map(h=><th key={h} className="whitespace-nowrap p-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=>{const x=results[i];return <tr key={`${r.system_id}:${r.batch_id}`} className={`border-b ${!r.include?"opacity-50":""}`}><td className="p-3"><input type="checkbox" aria-label={`Include ${r.cage_name} ${r.batch_name}`} checked={r.include} disabled={!!saved||busy} onChange={e=>change(i,"include",e.target.checked)}/></td><td className="p-3 font-medium whitespace-nowrap">{r.cage_name}</td><td className="p-3 whitespace-nowrap">{r.batch_name}</td><td className="p-3 whitespace-nowrap">{r.stock_date}</td><td className="p-2"><input aria-label={`Sampling date ${r.cage_name} ${r.batch_name}`} className="rounded-lg border bg-background p-2" type="date" max={cutoff} value={r.sample} disabled={!!saved||busy} onChange={e=>change(i,"sample",e.target.value)}/></td><td className="p-2"><input aria-label={`Starting fish ${r.cage_name} ${r.batch_name}`} title={`Database: ${r.stock_no} fish`} className={inputClass} type="number" min="0" max="10000000" step="1" value={r.stock} disabled={!!saved||busy} onChange={e=>change(i,"stock",e.target.value)}/></td><td className="p-2"><input aria-label={`Starting ABW ${r.cage_name} ${r.batch_name}`} title={`Measured: ${r.abw_g??"missing"} g`} className={inputClass} type="number" min="0.3" max="1000" step="any" value={r.abw} disabled={!!saved||busy} onChange={e=>change(i,"abw",e.target.value)}/></td>{[x?.end_fish,x?.end_abw_g,x?.feed_kg,x?.average_daily_kg].map((n,j)=><td key={j} className="p-3 text-right tabular-nums">{n==null?"—":fmt(n)}</td>)}</tr>})}</tbody></table></div>}
   <div className="flex flex-wrap justify-between items-center gap-3"><p className="font-semibold">{included.length} cages · {invalid?"Complete the inputs to total feed":`${fmt(total)} kg planned feed`}</p><button className="rounded-lg border px-4 py-2" disabled={invalid||!included.length} onClick={csv}>Export CSV</button></div>
  </section>
  {!saved&&rows.length>0?<div className="space-y-3"><label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>I have checked the live fish counts, ABWs and sampling dates for the included cages.</label><button className="rounded-lg bg-primary text-primary-foreground px-5 py-2 disabled:opacity-50" disabled={!canSave||busy||!confirmed||invalid||!included.length} onClick={async()=>{setBusy(true);setMessage("");try{const result=await saveFeedPlan({farm_id:farmId,starts_on:from,ends_on:to,source_as_of:cutoff,rows:included.map(r=>({system_id:r.system_id,batch_id:r.batch_id,stock_no:Number(r.stock),abw_g:Number(r.abw),sampled_on:r.sample}))});if(result.error)setMessage(result.error);else{setDirty(false);router.push(`/analytics/inputs/feed-planning?farmId=${farmId}&plan=${result.id}`)}}catch{setMessage("Could not save the plan. Please try again.")}finally{setBusy(false)}}}>{busy?"Saving…":"Save feed plan"}</button>{!canSave?<p className="text-sm text-muted-foreground">A farm manager or administrator can save plans.</p>:null}{invalid?<p role="alert" className="text-sm">Enter valid fish counts, ABWs and sampling dates for every included cage, or exclude incomplete rows.</p>:null}</div>:saved?<p className="text-sm text-muted-foreground">Saved {new Date(saved.created_at).toLocaleString("en-GB",{timeZone:"Africa/Nairobi"})}. </p>:null}
  {message?<p role="status">{message}</p>:null}
 </div>
}
